services:
    music-capsule:
        container_name: music-capsule
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3001:3001
        volumes:
            - ./public:/usr/src/app/public
        env_file:
            - .env
        dns:
            - 8.8.8.8
            - 8.8.4.4
